# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generated_pb2 as generated__pb2


class ReportingServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSpaceships = channel.unary_stream(
                '/ReportingServer/GetSpaceships',
                request_serializer=generated__pb2.Coordinates.SerializeToString,
                response_deserializer=generated__pb2.Spaceship.FromString,
                )


class ReportingServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSpaceships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportingServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSpaceships': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSpaceships,
                    request_deserializer=generated__pb2.Coordinates.FromString,
                    response_serializer=generated__pb2.Spaceship.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReportingServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReportingServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSpaceships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ReportingServer/GetSpaceships',
            generated__pb2.Coordinates.SerializeToString,
            generated__pb2.Spaceship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
