# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generated.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerated.proto\"\"\n\x0b\x43oordinates\x12\x13\n\x0b\x63oordinates\x18\x01 \x02(\t\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\x0c\n\x04rank\x18\x03 \x02(\t\"\x8e\x01\n\tSpaceship\x12\x11\n\talignment\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x12\n\nclass_type\x18\x03 \x02(\t\x12\x0e\n\x06length\x18\x04 \x02(\x02\x12\x11\n\tcrew_size\x18\x05 \x02(\x05\x12\r\n\x05\x61rmed\x18\x06 \x02(\x08\x12\x1a\n\x08officers\x18\x07 \x03(\x0b\x32\x08.Officer2>\n\x0fReportingServer\x12+\n\rGetSpaceships\x12\x0c.Coordinates\x1a\n.Spaceship0\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COORDINATES']._serialized_start=19
  _globals['_COORDINATES']._serialized_end=53
  _globals['_OFFICER']._serialized_start=55
  _globals['_OFFICER']._serialized_end=117
  _globals['_SPACESHIP']._serialized_start=120
  _globals['_SPACESHIP']._serialized_end=262
  _globals['_REPORTINGSERVER']._serialized_start=264
  _globals['_REPORTINGSERVER']._serialized_end=326
# @@protoc_insertion_point(module_scope)
